### ISSUE TITLE
报如下错误！

### ISSUE THREAD

**Issue by csh159** [angcyo/Android_Gradle_DSL_7.2.1#1]
* What went wrong:
Execution failed for task ':Android_Gradle_DSL_7.2.1:mergeReleaseJavaResource'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.MergeJavaResWorkAction
   > 2 files found with path 'META-INF/gradle-plugins/com.android.internal.asset-pack-bundle.properties' from inputs:
      - C:\Users\Administrator\.gradle\caches\modules-2\files-2.1\com.android.tools.build\gradle\7.2.1\51c17e0a7eea8eaaeb39b7e7a1e85a84867dcf2e\gradle-7.2.1.jar
      - C:\Users\Administrator\.gradle\caches\modules-2\files-2.1\com.android.tools.build\gradle\7.2.1\7daf5c3d8efddd5710872d8baa8c389509ca48d1\gradle-7.2.1-sources.jar
     Adding a packagingOptions block may help, please refer to
     https://developer.android.com/reference/tools/gradle-api/7.2/com/android/build/api/dsl/ResourcesPackagingOptions
     for more information

**Comment by angcyo** [comment]
这是一个分析工程, 编译没有意义.
